### ISSUE TITLE
[FR] Build documentation on-line 

### ISSUE THREAD

**Issue by sahilbhola14** [PinguDevTeam/ICF-MI-framework#31]
# Description of feature
So far, the documentation is being done locally for which scripts are already available.
Is it possible to automate the doc build state using git actions?

Correspondence: @dorukaks 

# Potential solution
Git actions

**Comment by dorukaks** [comment]
I'll create a branch out from `main` for this FR, this should not interfere with any of the other development items. Once this branch is done, we can merge with main and rebase dev :+1:
